// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Upgrade:                              1
// Endpoints:                           24
// Async Callback (empty):               1
// Total number of exported functions:  27

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    backendsc
    (
        init => init
        upgrade => upgrade
        getCandidateFee => candidate_fee
        updateCandidateFee => update_candidate_fee
        getElectionIDList => election_id_list
        getElectionData => election_data
        getRegisteredVoters => registered_voters
        getPotentialCandidateIDs => potential_candidate_id_list
        getCandidateIDs => candidate_id_list
        getCandidate => candidate
        getVotes => votes
        getDisputeIDList => dispute_id_list
        getDispute => dispute
        result_vector => result_vector
        results => results
        electionList => election_list
        registerElection => register_election
        submitCandidancy => submit_candidancy
        registerCandidate => register_candidate
        registerSelf => register_self
        registerVoter => register_voter
        vote => vote
        endElection => end_election
        makeDispute => make_dispute
        resolveDispute => resolve_dispute
        getCurrentBlockTimestamp => get_block_timestamp
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
