// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Upgrade:                              1
// Endpoints:                           16
// Async Callback (empty):               1
// Total number of exported functions:  19

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    backend_sc
    (
        init => init
        upgrade => upgrade
        getElectionIDList => election_id_list
        getElectionData => election_data
        getRegisteredVoters => registered_voters
        getCandidateIDs => candidate_id_list
        getCandidate => candidate
        getVotes => votes
        getDisputeIDList => dispute_id_list
        getDispute => dispute
        results => results
        electionList => election_list
        registerElection => register_election
        registerCandidate => register_candidate
        registerVoter => register_voter
        vote => vote
        endElection => end_election
        makeDispute => make_dispute
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
